#Makefile
include .env
PARAMS_FILE := $(strip $(params))
PARAMS_JSON := $(shell cat $(PARAMS_FILE))
DATA_SET := $(shell echo '$(PARAMS_JSON)' | jq -r '.data_set')


all: embeddings homology clustering selection vis
	@echo "Run Complete"
	
selection:
	@echo "Selecting Embeddings"
	@python src/selector.py

vis:
	@echo "Generating Visualizations"
	@python scripts/embedding_visualizations.py
	@python scripts/clustering_visualizations.py

embeddings:
	@echo "Generating Embeddings"
	@python scripts/embedding_generator.py

homology:
	@echo "Generating Persistence Diagrams"
	@python src/ripserer.py -i -1
	@python scripts/homology_generator.py

clustering:
	@echo "Computing Topolical Distances"
	@python src/clustering.py
clean:
	@rm -rf data/${DATA_SET}/