#Makefile
include .env
PARAMS_FILE := $(strip $(params))
EXPERIMENT := $(shell cat $(PARAMS_FILE) | shyaml get-value run_name)
DATASETS := $(shell cat $(PARAMS_FILE) | shyaml get-value data.dataset)


all: embeddings homology-transform quotient collapse 
	@echo "Run Complete"

setup: 
	@echo "Writing Config Files"
	@python src/setup.py

embeddings: setup
	@echo "Generating Embeddings"
	@python src/scripts/parallelize_embeddings.py

homology-transform:
	@echo "Generating Persistence Diagrams"
	@python src/scripts/parallelize_transforms.py

quotient:
	@echo "Computing Topolical Distances"
	@python src/scripts/parallelize_quotients.py

collapse:
	@echo "Selecting Embeddings"
	@python src/scripts/parallelize_collapse.py

vis:
	@echo "Generating Visualizations"
	@python scripts/embedding_visualizations.py
	@python scripts/quotient_visualizations.py
clean:
	@rm -rf data/*/${EXPERIMENT}/
	@rm -rf experiments/${EXPERIMENT}/

