run_name: BreastCancer-Diabetes
description: Are parameters stable here?
data:
  dataset:
  - diabetes
  - breast_cancer
  num_samples:
  - 100
  - 200
  - 300
  - 400
  num_clusters: 10
  seed: 442
embedding:
  model:
  - umap
  - isomap
  - phate
  - lle
  - tsne
  hyperparams:
    n_neighbors:
    - 10
    - 15
    - 20
    - 25
    - 30
    - 35
    init:
    - spectral
    dim:
    - 2
    min_dist:
    - 0.1
    - 0.5
    - 0.8
    early_exaggeration:
    - 10
    - 12
    - 14
    gamma:
    - 0.1
    - 0.25
    - 0.5
    - 0.75
    metric:
    - manhattan
    - euclidean
    - chebyshev
    reg:
    - 0.001
    - 0.01
random_seed: 42
topology:
  homology_max_dim: 1
  normalize: false
  filtration: alpha
  diagram_metric: landscape
  dendrogram_cut: 0.01
  linkage: average
